package com.aneke.peter.nigerianadministrativedivisionspinner.models

/*
* Model class to handle LGA object
*
*
* This can be modified to become a Room Entity, and might be in the near future
* when used as a Room Entity the "lgaId" property can be annotated as the primary key
* and autogenerated
*  The "stateId" should be used a Foreign key to join the resulting table to a
* the State table
* */

data class Lga(

    var lgaId: Int =0,

    val stateId: Int,

    val name: String
)