package com.aneke.peter.nigerianadministrativedivisionspinner.models


/*
* Model class to handle State object
*
*
* This can be modified to become a Room Entity, and might be in the near future
* when used as a Room Entity the "id" property can be annotated as the primary key
* and autogenerated and then used a Foreign key to join the resulting table to a
* the Local government area table
* */
data class State(

    var id: Int = 0,

    val name : String =""
)